// RESET PASSWORD EVENTS
export enum ResetPasswordEvent {
  FORGOT_PASSWORD,
  VERIFY_TOKEN,
  FIND_TOKEN_DETAILS,
  INVALIDATE_TOKEN,
  RESET_PASSWORD,
}

// AUTH SERVICE EVENTS
export enum AuthServiceEvents {
  AUTHENTICATE,
  UPDATE_USER_LOGO,
  ADD_USER_TO_ORGANIZATION,
  REMOVE_USER_FROM_ORGANIZATION,
  FIND_USER_BY_ORGANIZATION,
  FIND_USERS_BY_ORGANIZATION,
  FIND_USER_BY_ID,
  CREATE_USER_TO_ORGANIZATION,
}

// ORGANIZATION SERVICE EVENTS
export enum OrganizationServiceEvents {
  FIND_ORGANIZATION,
  UPDATE_ORGANIZATION_LOGO,
}

// NOTIFICATIONS SERVICE EVENTS
export enum NotificationsServiceEvents {
  FORGOT_PASSWORD,
  SUCCESSFUL_PASSWORD_CHANGED,
  SUCCESSFUL_REGISTRATION,
  USER_ADDED_TO_ORGANIZATION,
  USER_REMOVED_FROM_ORGANIZATION,
}

// CARS SERVICE EVENTS
export enum CarServiceEvents {
  ADD_CAR_PHOTOS,
  FIND_CAR_PHOTOS,
  FIND_CAR_PHOTO,
  DELETE_CAR_PHOTO,
  ADD_ORGANIZATION_CAR,
  FIND_ORGANIZATION_CARS,
  FIND_ORGANIZATION_CAR,
  UPDATE_ORGANIZATION_CAR,
  DELETE_ORGANIZATION_CAR,
  FIND_ORGANIZATION_CAR_BY_OWNER,
}

// FILES SERVICE EVENTS
export enum FileServiceEvents {
  DELETE_CAR_PHOTOS,
}
